### ISSUE TITLE
Missing "key" property

### ISSUE THREAD

**Issue by bo-kh** [OpusCapita/react-responsive-navbar#1]
When I use ResponsiveNavbar with a property showNavItemTooltip={false} I get a warning:

_Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of 'ResponsiveNavbar'._

**Button** element in 'navbarItem' function should be fixed the way as it is implemented in 'tooltipWrapper' function to use key property.

**Comment by skarjalainen** [comment]
Tested and working in the latest version
