### ISSUE TITLE
Menu item widths calculated incorrectly for long dynamic names

### ISSUE THREAD

**Issue by eriihine** [OpusCapita/react-responsive-navbar#2]
Responsive navbar no longer handles long dynamic names properly and the menu size is calculated incorrectly. This used to work in the older versions (e.g. 1.0.1), but not in the latest version.

There should be a min-width defined for displayed menu-item (e.g. as props).

![image](https://user-images.githubusercontent.com/7058178/37464288-8d0bbe7c-2860-11e8-9766-bac06c46e5e2.png)

Previously the long names were abbreviated with ellipsis.

![image](https://user-images.githubusercontent.com/7058178/37464561-5bba09b8-2861-11e8-8f29-f27b218c0964.png)

**Comment by skarjalainen** [comment]
Width calculations are fixed in the latest version
![image](https://user-images.githubusercontent.com/2102867/51111181-d50edb80-1803-11e9-98bb-da3530b96772.png)
